FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./apps/frontend ./apps/frontend
RUN bun run install

RUN bun run prisma:generate
RUN bun run build

EXPOSE 8080

CMD ["bun", "run", "start:frontend"]